version: "3.8"
services:
  # System services
  portainer:
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-vol:/data
    environment:
      - TZ=Europe/Moscow        
  wiki:
    image: arpaulnet/gollum
    ports:
      - 80:4567
    volumes:
      - wiki-vol:/wiki
    command: gollum --allow-uploads dir --h1-title
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow

  # iot services 
  home-assistant:
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - homeassistant-vol:/config
    environment:
      - TZ=Europe/Moscow
    privileged: true
    depends_on:
      - mqtt
    network_mode: "host"
    restart: unless-stopped
  hass-configurator:
    image: "causticlab/hass-configurator-docker:latest"
    restart: always
    ports:
      - "3218:3218/tcp"
    privileged: true
    environment:
      - HC_HASS_API=http://home-assistant:8123/api/
      - HC_HASS_WS_API=wss://home-assistant:8123/api/websocket
    volumes:
      - "./config/hass-configurator.settings.conf:/config/settings.conf"
      - "homeassistant-vol:/hass-config"
  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - nodered-vol:/data
      - /etc/localtime:/etc/localtime
      # - /home/pi/dev:/dev
    depends_on:
      - mqtt
      - influxdb
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mqtt-vol:/mosquitto
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped   
  zigbee:
    image: koenkk/zigbee2mqtt
    volumes:
      - zigbee-vol:/app/data
    ports:
      - "8080:8080"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: unless-stopped
    environment:
      - 'ZIGBEE2MQTT_CONFIG_MQTT_SERVER=mqtt://mqtt:1883'
      - 'ZIGBEE2MQTT_CONFIG_HOMEASSISTANT=true'
      - TZ=Europe/Moscow
    depends_on:
      - mqtt
  
  influxdb:
    image: arm32v7/influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-vol:/var/lib/influxdb
    restart: unless-stopped
    environment:
      - INFLUXDB_DB=db0
      # - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      # - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - chronograf-vol:/var/lib/chronograf
    depends_on:
      - influxdb
    restart: unless-stopped
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      # - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      # - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-vol:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    restart: unless-stopped
    depends_on:
      - influxdb
    # environment:
      # - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      # - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  # over


  
  # motioneye:
  #   image: ccrisan/motioneye:master-armhf
  #   ports:
  #     - 5000:8765
  #     - 8081:8081
  #   restart: unless-stopped
  #   volumes:
  #     - motion-vol:/etc/motion
  #     - motion-var-vol:/var/lib/motioneye
  #   environment:
  #     - TZ=Europe/Moscow

volumes:
  portainer-vol:
  mqtt-vol:
  zigbee-vol:
  nodered-vol:
  homeassistant-vol:
  wiki-vol:
  motion-vol:
  motion-var-vol:
  influxdb-vol:
  chronograf-vol:
  grafana-vol:
  
  
