version: "3.8"
services:
  # System services
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  # iot services 
  home-assistant:
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - /home/pi/homeassistant-conf:/config
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - mqtt
    network_mode: "host"
    restart: unless-stopped
  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - nodered-vol:/data
      - /etc/localtime:/etc/localtime
    depends_on:
      - mqtt
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mqtt-vol:/mosquitto
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped   
  zigbee:
    image: koenkk/zigbee2mqtt
    volumes:
      - zigbee-vol:/app/data
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    restart: unless-stopped
    environment:
      - 'ZIGBEE2MQTT_CONFIG_MQTT={"base_topic": "zigbee2mqtt", "server":"mqtt://mqtt:1883"}'
    depends_on:
      - mqtt
  zigbee2mqttAssistant:
    image: carldebilly/zigbee2mqttassistant
    environment:
      - Z2MA_SETTINGS__MQTTSERVER=mqtt
      # Set to your TimeZone when using on Linux https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      # Won't work if you're using the Windows version of the container
      - TZ=Europe/Moscow
    depends_on:
      - mqtt
      - zigbee
    ports:
      - 5555:80
    restart: unless-stopped

volumes:
  portainer_data:
  mqtt-vol:
    external: true
  zigbee-vol:
    external: true
  nodered-vol:
    external: true
  
